### ISSUE TITLE
Retire "entrypoint"

### ISSUE THREAD

**Issue by judepereira** [microservices/microservice.guide#12]
Consider the following microservice.yml:
```yaml
commands:
  publish:
    ...
  entrypoint:
    events:
      triggered:
```

Today, `entrypoint` allows you to execute a service without specifying a command. IMO this might be confusing for the following two reasons:
1. Loss of transparency - No command is specified - one must look at what the _entrypoint_ does in order to figure out the meaning of the execution
2. If there was a command which was meant to be there, but got lost in some form of refactoring, an unintended behaviour arises. If `entrypoint` is there, it gets executed, otherwise such an execution produces an error.

This issue is specifically for understanding the need to keep `entrypoint`, or have it removed in it's entirety.

### Pros for removing `entrypoint`
1. **Consistency**: Removing entrypoint will make all execution lines look the same, along with the actual HTTP requests.
2. **No assumptions**: The lack of a command in an execution line or a HTTP request makes somebody (either the Platform or the Service) parse a request differently.
3. **Opens up this keyword**: `entrypoint` as it stands today, is a reserved keyword under commands in microservice.yml. On the contrary, microservice.yml doesn't really need to have it at all. Users can openly use `entrypoint` as one of their own named commands and needn't worry about anything special happening.

@stevepeak @joshpollara @TomPed - I'd love to hear your opinions on this.

**Comment by TomPed** [comment]
I'm all about this, it will also remove some complexity with the `omg` cli. I'm in.
