### ISSUE TITLE
Secret files

### ISSUE THREAD

**Issue by stevepeak** [microservices/microservice.guide#41]
**Issue**

Take for example Google API's which need a `credentials.json` file for authentication. **How do I include this in the microservice?**

**Idea**

Data must be stored as base64 encoded and provided in an environment variable.
This would need to be added in documentation and a new key in the `environment` map for `encoding`.

**Comment by judepereira** [comment]
This is considered by the runtime using the OMG spec (as the runtime will provide the environment variables).
