### ISSUE TITLE
Needs docs for how services should handle errors

### ISSUE THREAD

**Issue by wilzbach** [microservices/microservice.guide#43]
Apparently, the following is the current convention:

```json
{success: false, error:<error string>}
```

Though imho they should use the respective HTTP error code and either return a string or optionally a more complex error object, s.t. the engine can take advantage of existing HTTP conventions and it needs to handle HTTP errors anyhow.

**Comment by judepereira** [comment]
The convention has now changed to use HTTP error codes.
