### ISSUE TITLE
Introduce OpenAPI support

### ISSUE THREAD

**Issue by stevepeak** [microservices/microservice.guide#54]
The [OpenAPI](https://github.com/OAI/) spec may be a popular solution to integrate with services. Utilizing the OpenAPI's community could help OMG grow and not repeat previous work.

Here is a simple example of how the OpenAPI could be used in the `microservice.yml`.

```yml
include:
  - file: openapi.spec.yaml
    type: OpenAPI
    
actions:
  pets: /pets
```
> See [petstore.yaml](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml) for example.

By including the spec the `microservice.yml` can fetch and validate the OpenAPI. Then developers could list actions by simply pointing to their endpoint in the OpenAPI.

#### `action -> output -> action`
The `output` of an action call may have new `actions`, but these are not exposed in the OpenAPI spec.

#### `action -> events`
The OpenAPI is not an event-driven spec and does not have support for API to Platform. This is ok, but should be noted that any actions that are event based may not use the OpenAPI.

#### Only `http`
The OpenAPI spec only supports HTTP. Other interfaces, such as HTTP, may not utilize the OpenAPI spec.

### Including files
The OpenAPI spec appears to not support multiple yaml files that combine into one spec. For example, the Kubernetes OpenAPI spec is >90k lines in one file... This can be solved by importing multiple files as suggested in the example, but it would be introducing something unsupported by OpenAPI OOB.

**Comment by judepereira** [comment]
This will be possible using the `openapi2omg` tool: https://github.com/microservices/openapi2omg

The OMG will not link to an openapi document, as the view layer (visually and in the IDE) will need to handle both formats. Instead, openapi paths will be converted using the tool mentioned above to OMG actions.
