### ISSUE TITLE
First load time is about 7 seconds

### ISSUE THREAD

**Issue by wilzbach** [microservices/microservice.guide#66]
Without a cache, it takes quite some time for the front page to be loaded:

![image](https://user-images.githubusercontent.com/4370550/55416717-a0dbc900-556f-11e9-8b47-9b01c8bb9574.png)

Any chance that we can compress the PNGs or serve SVGs?

**Comment by judepereira** [comment]
We've enabled asset optimisation (compress images, minify, etc) in the Netlify build settings. This has reduced the page size from 2.5 MB to 1.19 MB. The page loads in 1.03 seconds now.

 
![Screenshot 2019-08-13 at 17 55 56](https://user-images.githubusercontent.com/747087/62956698-ae457180-bdf3-11e9-85ef-45b287786aaf.png)
