### ISSUE TITLE
The examples are using outdated YAML

### ISSUE THREAD

**Issue by wilzbach** [microservices/microservice.guide#74]
e.g. https://microservice.guide/examples/http/pubsub/#handling-event-subscription

- it's now `actions`
- `help` in in the wrong part of the YAML

Here are two working examples:

- https://github.com/microservices/node-events
- https://github.com/microservices/python-events

**Comment by judepereira** [comment]
@wilzbach Events emitted by an action is still called `events`.

> `help` in in the wrong part of the YAML

Fixed.
