### ISSUE TITLE
Add note about RFC 2119

### ISSUE THREAD

**Issue by stevepeak** [microservices/microservice.guide#8]
Add the following snippet to the docs:

----

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119](https://tools.ietf.org/html/rfc2119).

**Comment by judepereira** [comment]
Already added.
